name: "Briefe eines Fallenden"
description: ""

url: '' 
baseurl: ''

source: .
destination: docs

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
paginate: 60
paginate_path: /page-:num

#disqus-id: your-disqus-id

sass:
    style: :compressed
    sass_dir: assets/css/

